### ISSUE TITLE
README do projeto

### ISSUE THREAD

**Issue by feokuma** [giordanGarci/workshop-springboot-mongodb#1]
Seria legal ter um README com algumas informações como:
- Descrição do projeto (o que descreveu no linkedin foi bem bom)
- Pré-requisitos para executar o projeto localmente (versões das ferramentas e links para instruções de instalação, caso necessário)
- Setup necessário para executar o projeto localmente (configurações de ambiente, containers, variáveis de ambiente, ...)
- Como executar os testes automatizados

Estas informações são ajudam bastante quem quiser depurar para ver como funciona a aplicação para entender a implementação

**Comment by giordanGarci** [comment]
Olá Fernando,

Muito obrigado pelo seu feedback e por se interessar pelo meu projeto. Criei um README com base no que você falou mas queria explicar algumas razões pelas quais pode não estar perfeito no momento:

1. **Testes Automatizados**: Por enquanto, o projeto não inclui testes automatizados. Tenho plena consciência da importância dos testes e pretendo adicioná-los em uma fase posterior do desenvolvimento.

2. **Configurações de Ambiente**: As configurações de ambiente podem variar dependendo do sistema operacional e das preferências de desenvolvimento de cada pessoa. Eu forneci orientações gerais para configuração do ambiente, mas entendo que essas informações podem não cobrir todos os casos possíveis.

Se você tiver mais sugestões ou comentários, fique à vontade para compartilhar, procuro sempre melhorar os meus projetos e documentações. Abraços!

**Comment by feokuma** [comment]
Boa! Estou começando a estudar o springboot e vou dar uma olhada no seu projeto. Com essas informações vou tentar rodar aqui na minha máquina com Linux e quem sabe eu consiga mandar algum PR. 🤓

Muito obrigado e parabéns pelos estudos.
